export type Locale = "en" | "pt";

const en = {
  skip: "Skip to content",
  skipOpen: "Skip introduction",
  newTab: "opens in a new tab",
  openLabel: "Healthcare Inspectorate Wales and Care Quality Commission pathway",
  nav: [
    { href: "#clinic", label: "Clinic" },
    { href: "#services", label: "Services" },
    { href: "#academy", label: "Academy" },
    { href: "#doctor", label: "Doctor" },
    { href: "#contact", label: "Contact" },
  ],
  book: "Book",
  bookLong: "Book a visit",
  themeToLight: "Switch to light theme",
  themeToDark: "Switch to dark theme",
  language: "Language",
  openKicker: "City Skin Doctor",
  regulatedBy: "Regulated by",
  hiw: "Healthcare Inspectorate Wales",
  cqc: "Care Quality Commission",
  paths: [
    { n: "01", k: "Medical", d: "Blood tests and the medical clinic." },
    { n: "02", k: "Surgical", d: "Hair transplant and cosmetic surgery." },
    { n: "03", k: "Cosmetic", d: "Laser, injectables, and weight-loss injections." },
  ],
  heroKicker: "Cardiff · London",
  heroTitle: ["Medical,", "Surgical &", "Cosmetic."],
  heroLede:
    "A doctor-led clinic for medical, surgical and cosmetic care, with a training academy alongside. Cardiff on City Road. London on Harrow Road.",
  heroCaption: "Dr Ebrahim Feghenaby",
  heroRole: "Founder & Medical Director",
  doctorAlt: "Dr Ebrahim Feghenaby, founder and Medical Director of City Skin Doctor",
  clinicAlt: "Published clinic plate from the City Skin Doctor About page",
  trifectaIndex: "02",
  trifectaEyebrow: "Pathways",
  trifectaTitle: "Medical, surgical, cosmetic.",
  trifectaLede: "Three quiet ways into the same regulated clinic.",
  trifecta: [
    {
      n: "01",
      k: "Medical",
      d: "Blood tests and the medical clinic. Quick, comprehensive results to help monitor health.",
      image: "blood" as const,
      alt: "Published blood test plate, City Skin Doctor",
    },
    {
      n: "02",
      k: "Surgical",
      d: "Hair transplant and cosmetic surgery, planned with the medical team.",
      image: "hair" as const,
      alt: "Published hair transplant plate, City Skin Doctor",
    },
    {
      n: "03",
      k: "Cosmetic",
      d: "Laser hair removal and rejuvenation, injectables, and weight-loss injections.",
      image: "laser1" as const,
      alt: "Published laser treatment plate, City Skin Doctor",
    },
  ],
  servicesIndex: "03",
  servicesEyebrow: "Services",
  servicesTitle: "The work of the clinic.",
  servicesLede: "Four home pathways, plus cosmetic surgery and skincare, as published.",
  readClinic: "Clinic page",
  laserTitle: "Laser Hair Removal & Rejuvenation",
  laserBody:
    "At our clinic, we proudly offer laser hair removal with the Candela GentleMax Pro, one of the most advanced and effective machines in the industry. We provide the gold standard in laser technology, ensuring safe, comfortable, and long-lasting results for all skin types. Experience the ultimate in hair removal with the best machine available.",
  laserAlt: "Laser hair removal treatment, published City Skin Doctor plate",
  laserAlt2: "Laser device plate, City Skin Doctor",
  services: [
    {
      id: "blood",
      title: "Blood Tests",
      body: "Visit our clinic for quick and comprehensive blood tests, providing accurate results to help monitor your health.",
      alt: "Blood sample plate published by City Skin Doctor",
      href: "https://www.cityskindoctor.co.uk/bloodtests",
    },
    {
      id: "hair",
      title: "Hair Transplant",
      body: "Restore your confidence with our advanced hair transplant services, delivering natural-looking.",
      alt: "Published hair transplant plate, City Skin Doctor",
      href: "https://www.cityskindoctor.co.uk/hair-transplant-1",
    },
    {
      id: "weight",
      title: "Weight Loss Injections",
      body: "Achieve your weight loss goals with our effective weight loss injections, designed to help you shed pounds.",
      alt: "Published weight loss injections plate, City Skin Doctor",
      href: "https://www.cityskindoctor.co.uk/weight-loss-injections",
    },
    {
      id: "cosmetic",
      title: "Cosmetic surgery",
      body: "Surgical aesthetic care, set beside the medical clinic and discussed in consultation.",
      alt: "Published cosmetic surgery plate, City Skin Doctor",
      href: "https://www.cityskindoctor.co.uk/beauty",
    },
    {
      id: "skin",
      title: "Skin care",
      body: "Signature skincare at the clinic, from cleansing treatments to the products on the shelf.",
      alt: "Published skincare treatment plate, City Skin Doctor",
      href: "https://www.cityskindoctor.co.uk/skin-care",
    },
  ],
  dualIndex: "04",
  clinicEyebrow: "Medical clinic",
  clinicTitle: "Care, under a named doctor.",
  clinicBody:
    "At City Skin Doctor, we provide a comprehensive range of medical and cosmetic services delivered by our team of experienced surgeon, dermatologists, and nurses. The clinic operates under strict regulatory standards and is accredited by both the Care Quality Commission (CQC) and Healthcare Inspectorate Wales (HIW).",
  clinicLink: "The clinic",
  academyEyebrow: "Training academy",
  academyKicker: "Your future is waiting for you, here...",
  academyTitle: "Become a beautician in under 3 months.",
  academyBody:
    "Sign up for one of the many FAST TRACK Academy Courses & receive a £100 BONUS towards our treatments! Offer valid until the end of March.",
  academyCpd: "Formally accredited CPD courses",
  academyLink: "Sign up",
  academyAlt: "Training Academy session at City Skin Doctor",
  productsIndex: "05",
  productsEyebrow: "The shelf",
  productsTitle: "Products that simply work…",
  productsLede: "Retail from the clinic store, beside the houses the team already uses.",
  store: "Visit our store",
  elixirAlt: "Collagen elixir from the City Skin Doctor store",
  cooperate: "In cooperation with",
  doctorIndex: "06",
  doctorEyebrow: "Medical Director",
  doctorTitle: "Dr Ebrahim Feghenaby",
  doctorP1:
    "Dr. Ebrahim Feghenaby graduated with an MD in 1997. His extensive NHS experience, working as a Senior Honorary Lecturer at Cardiff University, and current membership in the British College of Aesthetic Medicine are just a few examples of his rich knowledge, expertise, and achievements. He is the founder and Medical Director of City Skin Doctor Clinics and the Training Academy.",
  doctorP2:
    "Our expert team specializes in a wide range of skincare treatments and cosmetic services tailored to enhance your natural beauty. From advanced skin rejuvenation to non-surgical and surgical aesthetic procedures, we use the latest technologies and techniques to deliver personalized, safe, and effective results. Our mission is to help you feel confident and radiant, inside and out.",
  creds: [
    "MD, 1997",
    "NHS experience",
    "Senior Honorary Lecturer, Cardiff University",
    "British College of Aesthetic Medicine",
    "Founder & Medical Director",
  ],
  regIndex: "07",
  regEyebrow: "Regulation",
  regTitle: "HIW and CQC.",
  regBody:
    "The clinic is accredited by Healthcare Inspectorate Wales and the Care Quality Commission, the two regulators named on the published site.",
  hiwLink: "Healthcare Inspectorate Wales",
  cqcLink: "Care Quality Commission",
  catchIndex: "08",
  catchEyebrow: "Catchment",
  catchTitle: "Cardiff, Roath, London.",
  catchLede: "Two clinics. The Cardiff rooms on City Road also serve Roath. London is on Harrow Road.",
  chips: [
    { href: "#cardiff", label: "Cardiff · City Road" },
    { href: "#cardiff", label: "Roath" },
    { href: "#london", label: "London · Harrow Road" },
  ],
  contactIndex: "09",
  contactEyebrow: "Contact",
  contactTitle: "Book without the back-and-forth.",
  contactLede:
    "Please use our Booking system without the back-and-forth emails. If you would like further information, or to discuss your appointments email us at info@cityskindoctor.co.uk",
  caveat:
    "Please note: we don’t guarantee the exact time of each appointment booked and at times they might be delayed up to 4 hours. Also, some appointments might be cancelled/reschedule for emergency reasons.",
  hoursLabel: "Hours",
  hours: "Monday–Friday 10am–5pm",
  hoursSat: "Saturday 10am–4pm",
  phoneLabel: "Phone",
  emailLabel: "Email",
  cardiffName: "Cardiff",
  londonName: "London",
  roathNote: "Also the room for Roath.",
  disclaimer: "Design study. Not affiliated with City Skin Doctor.",
  built: "built by dglxss",
  instagram: "Instagram",
  facebook: "Facebook",
};

const pt: typeof en = {
  skip: "Saltar para o conteúdo",
  skipOpen: "Saltar a introdução",
  newTab: "abre num novo separador",
  openLabel: "Percurso Healthcare Inspectorate Wales e Care Quality Commission",
  nav: [
    { href: "#clinic", label: "Clínica" },
    { href: "#services", label: "Serviços" },
    { href: "#academy", label: "Academia" },
    { href: "#doctor", label: "Médico" },
    { href: "#contact", label: "Contacto" },
  ],
  book: "Marcar",
  bookLong: "Marcar consulta",
  themeToLight: "Mudar para o tema claro",
  themeToDark: "Mudar para o tema escuro",
  language: "Idioma",
  openKicker: "City Skin Doctor",
  regulatedBy: "Regulamentado por",
  hiw: "Healthcare Inspectorate Wales",
  cqc: "Care Quality Commission",
  paths: [
    { n: "01", k: "Médica", d: "Análises ao sangue e a clínica médica." },
    { n: "02", k: "Cirúrgica", d: "Transplante capilar e cirurgia cosmética." },
    { n: "03", k: "Cosmética", d: "Laser, injetáveis e injeções para perda de peso." },
  ],
  heroKicker: "Cardiff · Londres",
  heroTitle: ["Médica,", "cirúrgica", "e cosmética."],
  heroLede:
    "Uma clínica dirigida por um médico, para cuidados médicos, cirúrgicos e cosméticos, com uma academia de formação ao lado. Cardiff, na City Road. Londres, na Harrow Road.",
  heroCaption: "Dr Ebrahim Feghenaby",
  heroRole: "Fundador e diretor médico",
  doctorAlt: "Dr Ebrahim Feghenaby, fundador e diretor médico da City Skin Doctor",
  clinicAlt: "Placa publicada da clínica, página About da City Skin Doctor",
  trifectaIndex: "02",
  trifectaEyebrow: "Percursos",
  trifectaTitle: "Médica, cirúrgica, cosmética.",
  trifectaLede: "Três entradas calmas para a mesma clínica regulamentada.",
  trifecta: [
    {
      n: "01",
      k: "Médica",
      d: "Análises ao sangue e a clínica médica. Resultados rápidos e completos para acompanhar a saúde.",
      image: "blood",
      alt: "Placa publicada de análises ao sangue, City Skin Doctor",
    },
    {
      n: "02",
      k: "Cirúrgica",
      d: "Transplante capilar e cirurgia cosmética, planeados com a equipa médica.",
      image: "hair",
      alt: "Placa publicada de transplante capilar, City Skin Doctor",
    },
    {
      n: "03",
      k: "Cosmética",
      d: "Depilação e rejuvenescimento a laser, injetáveis e injeções para perda de peso.",
      image: "laser1",
      alt: "Placa publicada de tratamento a laser, City Skin Doctor",
    },
  ],
  servicesIndex: "03",
  servicesEyebrow: "Serviços",
  servicesTitle: "O trabalho da clínica.",
  servicesLede: "Quatro percursos da página inicial, mais cirurgia cosmética e cuidados de pele, como publicado.",
  readClinic: "Página da clínica",
  laserTitle: "Depilação a laser e rejuvenescimento",
  laserBody:
    "Na nossa clínica oferecemos depilação a laser com o Candela GentleMax Pro, uma das máquinas mais avançadas e eficazes do setor. Disponibilizamos o padrão de referência em tecnologia laser, com resultados seguros, confortáveis e duradouros para todos os tipos de pele. A depilação com a melhor máquina disponível.",
  laserAlt: "Tratamento de depilação a laser, placa publicada da City Skin Doctor",
  laserAlt2: "Placa do aparelho de laser, City Skin Doctor",
  services: [
    {
      id: "blood",
      title: "Análises ao sangue",
      body: "Visite a nossa clínica para análises rápidas e completas, com resultados precisos que ajudam a acompanhar a sua saúde.",
      alt: "Placa de análises ao sangue publicada pela City Skin Doctor",
      href: "https://www.cityskindoctor.co.uk/bloodtests",
    },
    {
      id: "hair",
      title: "Transplante capilar",
      body: "Restaure a sua confiança com os nossos serviços avançados de transplante capilar, de aspeto natural.",
      alt: "Placa publicada de transplante capilar, City Skin Doctor",
      href: "https://www.cityskindoctor.co.uk/hair-transplant-1",
    },
    {
      id: "weight",
      title: "Injeções para perda de peso",
      body: "Alcance os seus objetivos de perda de peso com as nossas injeções eficazes, pensadas para o ajudar a perder peso.",
      alt: "Placa publicada de injeções para perda de peso, City Skin Doctor",
      href: "https://www.cityskindoctor.co.uk/weight-loss-injections",
    },
    {
      id: "cosmetic",
      title: "Cirurgia cosmética",
      body: "Cuidado estético cirúrgico, junto da clínica médica e discutido em consulta.",
      alt: "Placa publicada de cirurgia cosmética, City Skin Doctor",
      href: "https://www.cityskindoctor.co.uk/beauty",
    },
    {
      id: "skin",
      title: "Cuidados de pele",
      body: "Skincare de assinatura na clínica, dos tratamentos de limpeza aos produtos da prateleira.",
      alt: "Placa publicada de tratamento de pele, City Skin Doctor",
      href: "https://www.cityskindoctor.co.uk/skin-care",
    },
  ],
  dualIndex: "04",
  clinicEyebrow: "Clínica médica",
  clinicTitle: "Cuidado, com um médico nomeado.",
  clinicBody:
    "Na City Skin Doctor oferecemos uma gama completa de serviços médicos e cosméticos, prestados pela nossa equipa de cirurgião, dermatologistas e enfermeiros. A clínica trabalha sob normas regulamentares rigorosas e está acreditada pela Care Quality Commission (CQC) e pela Healthcare Inspectorate Wales (HIW).",
  clinicLink: "A clínica",
  academyEyebrow: "Academia de formação",
  academyKicker: "O seu futuro está à sua espera, aqui...",
  academyTitle: "Torne-se esteticista em menos de 3 meses.",
  academyBody:
    "Inscreva-se num dos muitos cursos FAST TRACK da Academia e receba um bónus de £100 para os nossos tratamentos! Oferta válida até ao fim de março.",
  academyCpd: "Cursos CPD formalmente acreditados",
  academyLink: "Inscrever",
  academyAlt: "Sessão da Training Academy na City Skin Doctor",
  productsIndex: "05",
  productsEyebrow: "A prateleira",
  productsTitle: "Produtos que simplesmente funcionam…",
  productsLede: "Retalho da loja da clínica, ao lado das casas que a equipa já utiliza.",
  store: "Visite a nossa loja",
  elixirAlt: "Elixir de colagénio da loja City Skin Doctor",
  cooperate: "Em cooperação com",
  doctorIndex: "06",
  doctorEyebrow: "Diretor médico",
  doctorTitle: "Dr Ebrahim Feghenaby",
  doctorP1:
    "O Dr. Ebrahim Feghenaby formou-se em Medicina em 1997. A sua experiência no NHS, o trabalho como Senior Honorary Lecturer na Universidade de Cardiff e a atual filiação no British College of Aesthetic Medicine são alguns exemplos do seu conhecimento, experiência e percurso. É o fundador e diretor médico das clínicas City Skin Doctor e da Training Academy.",
  doctorP2:
    "A nossa equipa especializa-se numa ampla gama de tratamentos de pele e serviços cosméticos pensados para realçar a beleza natural. Do rejuvenescimento avançado a procedimentos estéticos não cirúrgicos e cirúrgicos, usamos tecnologias e técnicas atuais para resultados personalizados, seguros e eficazes. A missão é ajudar cada pessoa a sentir-se confiante, por dentro e por fora.",
  creds: [
    "MD, 1997",
    "Experiência no NHS",
    "Senior Honorary Lecturer, Universidade de Cardiff",
    "British College of Aesthetic Medicine",
    "Fundador e diretor médico",
  ],
  regIndex: "07",
  regEyebrow: "Regulamentação",
  regTitle: "HIW e CQC.",
  regBody:
    "A clínica está acreditada pela Healthcare Inspectorate Wales e pela Care Quality Commission, os dois reguladores indicados no site publicado.",
  hiwLink: "Healthcare Inspectorate Wales",
  cqcLink: "Care Quality Commission",
  catchIndex: "08",
  catchEyebrow: "Área",
  catchTitle: "Cardiff, Roath, Londres.",
  catchLede:
    "Duas clínicas. As salas de Cardiff, na City Road, servem também Roath. Londres fica na Harrow Road.",
  chips: [
    { href: "#cardiff", label: "Cardiff · City Road" },
    { href: "#cardiff", label: "Roath" },
    { href: "#london", label: "Londres · Harrow Road" },
  ],
  contactIndex: "09",
  contactEyebrow: "Contacto",
  contactTitle: "Marque sem o vai-e-vem de emails.",
  contactLede:
    "Use o sistema de marcações sem o vai-e-vem de emails. Se quiser mais informação, ou falar sobre a sua marcação, escreva para info@cityskindoctor.co.uk",
  caveat:
    "Nota: não garantimos a hora exata de cada marcação e, por vezes, pode haver atrasos até 4 horas. Algumas marcações podem ser canceladas ou remarcadas por motivos de emergência.",
  hoursLabel: "Horário",
  hours: "Segunda a sexta, 10h–17h",
  hoursSat: "Sábado, 10h–16h",
  phoneLabel: "Telefone",
  emailLabel: "Email",
  cardiffName: "Cardiff",
  londonName: "Londres",
  roathNote: "Também a sala para Roath.",
  disclaimer: "Estudo de design. Sem afiliação com a City Skin Doctor.",
  built: "feito pela dglxss",
  instagram: "Instagram",
  facebook: "Facebook",
};

export const copy = { en, pt };
export type Copy = typeof en;
